#Hi! Here is everything documented! (I hope)

#Possible Language: en_US
lang: 'en_US'

#Allow bedspawn?
allow-bed: 'true'

#Compass pointing to bedspawn
allow-compass-bed: 'false'

#Allow max homes, define a list here. The player will need the permission "utilizen.group.[groupname]"
#to be allowed to set homes. The number after : determines the allowed number of homes.
#Your group name MUST be exactly the same as the group name of your permission plugin.
#This list will be used to determine the group orders (e.g. when applying a chat prefix)
#The first item in the list should be the highest group, the last one should be the lowest
#You need that also for other parts of Utilizen which needs this group system (example: prefixes & suffixes). 
#So you should fill it up.
homes:
  - 'admin:7'
  - 'moderator:5'
  - 'member:4'

#Default home limit if the player does not have any of the above groups
default: '3'

#Set the home limit for operators
op-homes: '5'

#Set the standard ban reason, if no reason is specified
banreason: 'You were banned'

#Set the standard kick reason, if no reason is specified
kickreason: 'You were kicked'

#Kick operators on /kickall?
kickops: 'false'

#Enable enchantments over the vanilla max level
enchants: 'false'

#Show prefix and suffix in TabList
tablist: 'false'

#You can use following Tags here:
#<player.list_name> returns player's name as shown in the player list
#<player.name> returns player's Minecraft name
#<player.display_name> returns the player's nickname (if nicked)
#<server.list_online_players.size> returns the number of online players
#<server.max_players> returns the total number of player slots for this server
motd:
  - "<&3>Welcome <&b><player.list_name><&3>!"
  - "<&3>You are looking good today!"
  - "<&3>There are <&b><server.list_online_players.size><&3>/<&b><server.max_players> <&3>people Online!"