#This is the Chatformat section of Utilizen.
#You should follow this format to make your own formatting
#You don't wanna touch line 28 & 29
#Put the highest group first, and the lowest group last, OP's always get the highest permission
#Owner -> Admin -> Moderator -> Supporter -> Member
#
#Following tags are recommended:
#<server.group_prefix[<groupname>].parse_color> returns the prefix of the group from your permission plugin, parsed with colors
#<server.group_suffix[<groupname>].parse_color> returns the suffix of the group from your permission plugin, parsed with colors
#<player.list_name> returns the name from the tablist
#<player.display_name> returns the nickname of the player
#<player.name> returns the player's original name (not nicked)
#<text> to get the chat output - you need that in any format: part
#put colors in a <> like <&a>
UtilizenChat:
    type: world
    debug: false
    events:
        on player chats:
        - if <player.has_flag[jailed]>:
          - determine FORMAT:UtilizenFormatJailed
        - else if <player.has_permission[utilizen.group.admin]>:
          - determine FORMAT:UtilizenFormatAdmin
        - else if <player.has_permission[utilizen.group.moderator]>:
          - determine FORMAT:UtilizenFormatModerator
        - else if <player.has_permission[utilizen.group.member]>:
          - determine FORMAT:UtilizenFormatMember
        - else:
          - determine FORMAT:UtilizenFormatDefault
UtilizenFormatDefault:
    type: format
    debug: false
    format: <server.group_prefix[default]> <&r><player.display_name><&r> > <text>
UtilizenFormatAdmin:
    type: format
    debug: false
    format: <&a>[Admin] <&r><player.display_name><&r> > <text>
UtilizenFormatModerator:
    type: format
    debug: false
    format: <&1>[Moderator] <&r><player.list_name><&r> > <text>
UtilizenFormatMember:
    type: format
    debug: false
    format: <&2>[Member] <&r><player.list_name><&r> > <text>
UtilizenFormatJailed:
    type: format
    debug: false
    format: <&6>[Jailed] <&e><player.list_name><&r> > <text>